Dev/wei
raytso/TesoraShot pull request #2
Opened 2019-02-19 09:32 UTC by Wei18

2019-02-19 18:53 UTC, raytso commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +        [Link](https://leetcode.com/problems/third-maximum-number/)
👍

2019-02-19 19:01 UTC, raytso commented on TesoraShot/Solutions/Ray/SolutionsRay.swift
> +    }
Not sure how to do this properly.. we'll leave it as is for now

2019-02-19 19:06 UTC, raytso requested changes

2019-02-19 19:06 UTC, raytso commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +     Input: [3, 2, 1
missing end bracket

2019-02-19 19:06 UTC, raytso commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +     - Returns: The third maximum number in this array; the maximum number otherwise.
Should be:
```
- Returns: The ideal third maximum number within given input.
```

2019-02-19 19:06 UTC, raytso commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +
Please add callout:
```
- Complexity: *O(n)*
```

2019-02-19 19:06 UTC, raytso commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +
Please add full description:
```
Returns the third maximum number within given array. If it does not exist, returns the maximum number.
```

2019-02-19 19:11 UTC, raytso commented
it would be better to squash the first three commits into a single setup, but that's up to you.

2019-02-20 00:52 UTC, Wei18 commented on TesoraShot/Solutions/SolutionsProtocol.swift
> +     - Returns: The third maximum number in this array; the maximum number otherwise.
... but your answer is missing if array count less than 3, return the maximum number.

2019-02-20 05:11 UTC, raytso approved these changes

2019-02-20 05:15 UTC, merged